---
title: Max Determinant
author: 'Enrique Pérez Herrero'
date: '2022-03-05'
slug: []
categories: ["math"]
tags: ["algebra", "determinant"]
featured:
  url: plot3dmaxmatrix.png
  alt: Plot3D of max matrix elements
  caption: Plot3D of max matrix elements
  credit: Psychedelic Geometry
  previewOnly: false
---

Formulas for the determinants of special square matrices with elements max or min, between the indices of the elements.

<!--more-->

The sequence [A181983](https://oeis.org/A181983)(n) gives the determinants of
the square matrices: $M_{n}$,  with elements $m_{i,j}= \max(i,j)$, where $\max$
the is the maximum function.

This identity looks as follows:

$$ det{\bigg[ max(i,j) \bigg] }_{1\leq i,j \leq n} = -n \cdot {(-1)}^{n} = A181983(n) $$

# Proof


We can build a new matrix with the same determinant subtracting row $i$ from row $i+1$, starting at the 2nd row, and then we can compute this determinant using the technique of expansion by minors at element $m_{1,n}$

We can show this proof better with an example:

We can transform:

$$ M_{10} = \left(\begin{array}{cccccccccc} 
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \\
2 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \\
3 & 3 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \\
4 & 4 & 4 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \\
5 & 5 & 5 & 5 & 5 & 6 & 7 & 8 & 9 & 10 \\
6 & 6 & 6 & 6 & 6 & 6 & 7 & 8 & 9 & 10 \\
7 & 7 & 7 & 7 & 7 & 7 & 7 & 8 & 9 & 10 \\
8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 & 9 & 10 \\
9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 10 \\
10 & 10 & 10 & 10 & 10 & 10 & 10 & 10 & 10 & 10
\end{array} \right) $$

into:

$$M^{*}_{10} =\left(\begin{array}{cccccccccc}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \\
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 0 & 0 \\
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 0 \end{array} \right)$$

We can generalize this proof to a very similar kind of matrices, 
getting:

$$ det{\bigg[ max(i,j)^k \bigg]}_{1\leq i,j \leq n} = {(-1)}^{n-1} \cdot n^{k} \cdot \prod_{s=1}^{n-1}{(s+1)^k-s^k} $$

$$ det{\bigg[ min(i,j)^k \bigg]}_{1\leq i,j \leq n} = \prod_{s=1}^{n-1}{(s+1)^k-s^k} $$

# References:
[1] - N. J. A. Sloane, The On-Line Encyclopedia of Integer Sequences. [A051125](https://oeis.org/A051125): Table T(n,k) = max{n,k} read by antidiagonals (n >= 1, k >= 1).    
[2] - Michael Somos, Apr 04 2012, The On-Line Encyclopedia of Integer Sequences. [A181983](https://oeis.org/A181983): ```-(-1)^n * n.```    
[3] - Emeric Deutsch, Jun 05 2009, The On-Line Encyclopedia of Integer Sequences. [A161124](https://oeis.org/A161124): Number of inversions in all fixed-point-free involutions of {1,2,...,2n}.    
[4] - N. J. A. Sloane, The On-Line Encyclopedia of Integer Sequences. [A001147](https://oeis.org/A001147): Double factorial of odd numbers: ```(2*n-1)!! = 1*3*5*...*(2*n-1) ```   
</style>